# Generated by Django 4.2.16 on 2024-11-02 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habot_employee_app', '0002_habotauthtoken_authtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habotauthtoken',
            name='user_id',
            field=models.CharField(max_length=12),
        ),
    ]
